general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13.5

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[window]
padding = { x = 10, y = 2 }
# decorations = "none"
